### ISSUE TITLE
Installer is locked while installing on the server

### ISSUE THREAD

**Issue by thinkfair** [Tecdiary/EmailTestingApp#3]
Hi
I have worked on app in a local system and the same folder I have uploaded on the server including database but it is not working and showing the error while installing "Installer is locked! Please contact your developer/support."

Please resolve the issue asap.

**Comment by thinkfair** [comment]
techdiary advance stock manager

**Comment by MianSaleem** [comment]
Hello,

Installer locked means the installation was performed. If you want to re-install, please upload the files as you did the first time. 

Please ask on support portal [https://tecdiary.net/support](https://tecdiary.net/support) as this is only for Email Testing App.

Thank you
